# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
#Agrego
from backend import FloatingPoint2Dec, Dec2FloatingPoint
#_____________________________________________________________

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(953, 505)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 200, 251, 251))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 70, 131, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.b32 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.b32.setFont(font)
        self.b32.setObjectName("b32")
        self.verticalLayout.addWidget(self.b32)
        self.b16 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.b16.setFont(font)
        self.b16.setObjectName("b16")
        self.verticalLayout.addWidget(self.b16)
        self.b64 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.b64.setFont(font)
        self.b64.setObjectName("b64")
        self.verticalLayout.addWidget(self.b64)
        self.b128 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.b128.setFont(font)
        self.b128.setObjectName("b128")
        self.verticalLayout.addWidget(self.b128)
        self.b256 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.b256.setFont(font)
        self.b256.setObjectName("b256")
        self.verticalLayout.addWidget(self.b256)
        self.lcdNumber = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber.setGeometry(QtCore.QRect(160, 80, 81, 41))
        self.lcdNumber.setObjectName("lcdNumber")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(300, 230, 621, 91))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.textExponente = QtWidgets.QTextBrowser(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.textExponente.setFont(font)
        self.textExponente.setObjectName("textExponente")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.textExponente)
        self.textMantisa = QtWidgets.QTextBrowser(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.textMantisa.setFont(font)
        self.textMantisa.setObjectName("textMantisa")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.textMantisa)
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(300, 330, 621, 121))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 120, 881, 81))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.buttonConvertirFPHex = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.buttonConvertirFPHex.setObjectName("buttonConvertirFPHex")
        self.gridLayout.addWidget(self.buttonConvertirFPHex, 1, 2, 1, 1)
        self.buttonConvertirDec = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.buttonConvertirDec.setObjectName("buttonConvertirDec")
        self.gridLayout.addWidget(self.buttonConvertirDec, 2, 2, 1, 1)
        self.ioDecimal = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ioDecimal.sizePolicy().hasHeightForWidth())
        self.ioDecimal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.ioDecimal.setFont(font)
        self.ioDecimal.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.ioDecimal.setText("")
        self.ioDecimal.setObjectName("ioDecimal")
        self.gridLayout.addWidget(self.ioDecimal, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.ioHexa = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ioHexa.sizePolicy().hasHeightForWidth())
        self.ioHexa.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.ioHexa.setFont(font)
        self.ioHexa.setObjectName("ioHexa")
        self.gridLayout.addWidget(self.ioHexa, 1, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 10, 881, 111))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.ioBinario = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ioBinario.sizePolicy().hasHeightForWidth())
        self.ioBinario.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.ioBinario.setFont(font)
        self.ioBinario.setObjectName("ioBinario")
        self.horizontalLayout.addWidget(self.ioBinario)
        self.buttonConvertirFP = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.buttonConvertirFP.setObjectName("buttonConvertirFP")
        self.horizontalLayout.addWidget(self.buttonConvertirFP)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 953, 20))
        self.menubar.setObjectName("menubar")
        self.menua = QtWidgets.QMenu(self.menubar)
        self.menua.setObjectName("menua")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menua.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #AGREGO
        self.buttonConvertirFP.clicked.connect(self.calc2Decimal)
        self.buttonConvertirDec.clicked.connect(self.calc2FP)  

        #_________________________________________________________

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Cantidad de bits"))
        self.b32.setText(_translate("MainWindow", "16 bits"))
        self.b16.setText(_translate("MainWindow", "32 bits"))
        self.b64.setText(_translate("MainWindow", "64 bits"))
        self.b128.setText(_translate("MainWindow", "128 bits"))
        self.b256.setText(_translate("MainWindow", "256 bits"))
        self.label_4.setText(_translate("MainWindow", "Exponente"))
        self.label_5.setText(_translate("MainWindow", "Mantisa"))
        self.textExponente.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cambria Math\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p></body></html>"))
        self.textMantisa.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cambria Math\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; text-decoration: underline;\">Instrucciones</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Conversión de punto flotante a decimal: ingrese el número en binario o hexadecimal con longitudes de 16, 32, 64, 128 o 256 bits y presione el botón &quot;Convertir&quot; correspondiente.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Conversión de decimal a punto flotante: ingrese el número decimal, seleccione la cantidad de bits de punto flotante que quiere obtener y presione convertir.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Ejemplo de número decimal: -4.5 ; -34.7e-32 ; 243.3E2</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "Hexadecimal:"))
        self.buttonConvertirFPHex.setText(_translate("MainWindow", "Convertir"))
        self.buttonConvertirDec.setText(_translate("MainWindow", "Convertir"))
        self.label_2.setText(_translate("MainWindow", "Decimal:"))
        self.label.setText(_translate("MainWindow", "Binario:         "))
        self.ioBinario.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cambria Math\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.buttonConvertirFP.setText(_translate("MainWindow", "Convertir"))
        self.menua.setTitle(_translate("MainWindow", "Conversor Punto Flotante - Decimal"))

    #Agrego
    def calc2Decimal(self):
        fp = self.ioBinario.toPlainText()
        output = FloatingPoint2Dec(fp)
        if output == 'error-nbits':
            self.ioDecimal.setText('Error: la cantidad de bits debe ser 16, 32, 64, 128 o 256.')
            self.lcdNumber.display(len(fp))
        elif output == 'error-not-number':
            self.ioDecimal.setText('Error: debe ingresa un número binario.')
        else:
            self.ioHexa.setText(hex(int(fp,2))[2:]) #entrada en hexa
            self.ioDecimal.setText(str(output)) #resultado decimal
            self.lcdNumber.display(len(fp))

    def calc2FP(self):
        b = self.nBits()
        if b != -1:
            d = self.ioDecimal.text()
            output = Dec2FloatingPoint(d,b)
            if output == 'error-not-number':
                self.ioBinario.setText('Error: debe ingresar un número decimal válido')
            elif output.isnumeric():
                self.ioBinario.setText(output);
                self.ioHexa.setText(hex(int(output,2))[2:])
                self.lcdNumber.display(len(output))
            else:
                self.ioBinario.setText(output);
                self.ioHexa.setText('')
        else:
            self.ioBinario.setText('Error: debe seleccionar la cantidad de bits para punto flotante')
	
    def nBits(self):
        if self.b16.isChecked():
            return 32 #me equivoque en el designer
        elif self.b32.isChecked():
            return 16 #me equivoque en el designer
        elif self.b64.isChecked():
            return 64
        elif self.b128.isChecked():
            return 128
        elif self.b256.isChecked():
            return 256
        else:
            return -1
    #_____________________

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
